name: VsFullCleanupCI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  # Build job
  build:
    runs-on: [windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore NuGet packages
      run: nuget restore DirectoryCleanup.sln
      
    - name: Build Solution
      run: msbuild DirectoryCleanup.sln /p:Configuration=Release

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-without-markdown
        path: DirectoryCleanup/bin/x86/Release/DirectoryCleanup.exe
        retention-days: 5
